name: Deploy

on:
  push:
    tags:
      # Matches tags that have the shape `vX.Y.Z`. Reference:
      # https://help.github.com/en/articles/workflow-syntax-for-github-actions#onpushpull_requesttagsbranches
      - 'v[0-9]+.[0-9]+.[0-9]+'

      # Ignore tags that use a preid after `vX.Y.Z`, for example: vX.Y.Z-alpha.0
      # https://help.github.com/en/articles/workflow-syntax-for-github-actions#example-using-positive-and-negative-patterns
      - '!v[0-9]+.[0-9]+.[0-9]+-*'
  workflow_dispatch:

jobs:
  deploy:
    name: Production
    if: ${{ github.repository == 'primer/react' }}
    uses: primer/.github/.github/workflows/deploy.yml@0cec9b9914f358846163f2428663b58da41028c9
    permissions:
      contents: read
      pages: write
      id-token: write
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}
    with:
      node_version: 18
      install: npm ci && cd docs && npm ci --legacy-peer-deps && cd ..
      build: npm run build:docs
      output_dir: docs/public
